### ISSUE TITLE
Unknown module(s): 'cmi_cmiecom'

### ISSUE THREAD

**Issue by Kiwifu** [taoufiqaitali/magento2-cmi-maroctelecommerce#1]
Hi,

We faced an error when extract the files by ftp, When running CLI command to activate the extension I got : 

$ php bin/magento module:enable cmi_cmiecom
Unknown module(s): 'cmi_cmiecom'

Can you help?

**Comment by Kiwifu** [comment]
@taoufiqaitali any help?

**Comment by taoufiqaitali** [comment]
@Kiwifu you followed manual installation?!
https://github.com/taoufiqaitali/magento2-cmi-maroctelecommerce#manual-installation
Make sur files in folder app/code/cmi/cmiecom/ lower case 
You can run directly setup:upgrade
